title: obaid's longer thoughts
author: obaid
email: me@obaid.wtf
description: >-
  politics + systems + economics + markets + binary technologies + innovation + sciences + futbol + overton window/pop culture
  this is very prone to change as I add, drop more interests

baseurl: ""
url: "https://obaidregens.github.io"
timezone: Asia/Karachi

# Build settings
remote_theme: jekyll/minima

minima:
  hide_site_feed_link: true
  social_links:
    - title: Obaid on LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/wtfobaid/"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
